### ISSUE TITLE
num值过大导致栈溢出

### ISSUE THREAD

**Issue by qwerdome** [AutumnFish/testApi#6]
url:http://127.0.0.1:8888/joke/list?num=9999<br>
![image](https://user-images.githubusercontent.com/74087938/195773563-537923ca-28ff-4501-a10c-3f8687ec9f33.png)

**Comment by AutumnFish** [comment]
已修复，可以重新测试哈

**Comment by AutumnFish** [comment]
关掉了

**Comment by AutumnFish** [comment]
已修复，可以重新测试一下
